
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "app.deployment.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.ssh.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ include "app.deployment.name" . }}
  {{- if or .Values.deployment.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.deployment.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.deployment.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: {{ include "app.deployment.name" . }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: {{ include "app.deployment.name" . }}
      {{- if .Values.deployment.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.deployment.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: sshd
          persistentVolumeClaim:
            claimName: {{ include "app.pvc.sshd.name" . }}
        - name: ssh
          persistentVolumeClaim:
            claimName: {{ include "app.pvc.ssh.name" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "app.pvc.data.name" . }}
      {{- include "common.images.pullSecrets" (dict "images" (list .Values.deployment.image)) | nindent 6 -}}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            {{- toYaml .Values.logic.ensureRepos | nindent 12 }}
          securityContext:
            {{- toYaml .Values.deployment.containerSecurityContext | nindent 12 }}
          image: {{ include "app.image" . }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          volumeMounts:
            - name: sshd
              mountPath: /etc/ssh
              readOnly: true
            - name: ssh
              mountPath: /var/svn/.ssh
              readOnly: true
            - name: data
              mountPath: /var/svn/repos
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          {{- if .Values.deployment.resources }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
