
{{- if .Values.persistence.sshd.storageClass }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.pvc.sshd.name" }}
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.sshd.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "app.pvc.sshd.name" }}
  annotations:
    {{- if .Values.persistence.sshd.resourcePolicy }}
    helm.sh/resource-policy: {{ .Values.Values.persistence.sshd.resourcePolicy | quote }}
    {{- end }}
    {{- if or .Values.persistence.sshd.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.sshd.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.sshd.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.sshd.size }}
  resources:
    requests:
      storage: {{ .Values.persistence.sshd.size | quote }}
  {{- end }}
  {{ include "common.storage.class" (dict "persistence" .Values.persistence.sshd "global" .Values.global) }}
{{- end }}
