
{{- if .Values.persistence.ssh.storageClass }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.pvc.ssh.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.ssh.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ include "app.pvc.ssh.name" . }}
  annotations:
    {{- if .Values.persistence.ssh.resourcePolicy }}
    helm.sh/resource-policy: {{ .Values.Values.persistence.ssh.resourcePolicy | quote }}
    {{- end }}
    {{- if or .Values.persistence.ssh.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.ssh.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.ssh.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.ssh.size }}
  resources:
    requests:
      storage: {{ .Values.persistence.ssh.size | quote }}
  {{- end }}
  {{ include "common.storage.class" (dict "persistence" .Values.persistence.ssh "global" .Values.global) }}
{{- end }}
